name: Deploy Gatsby site

on:
  workflow_dispatch:
  push:
    branches:
      - "master"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: public
          path: ./public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          timeout: 600000
          error_count: 10
          reporting_interval: 5000
          artifact_name: public
          preview: false
