name: Gatsby Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # Mengatur Node.js versi 18

      - name: Install dependencies
        run: yarn install

      - name: Build Gatsby site
        env:
          NODE_TLS_REJECT_UNAUTHORIZED: 0
          NODE_OPTIONS: "--max-old-space-size=4096"
        run: |
          sed -i 's/unstable_shouldOnCreateNode/shouldOnCreateNode/g' node_modules/gatsby-plugin-mdx/gatsby-node.js
          yarn build

      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
