name: Deploy Gatsby

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        continue-on-error: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
        continue-on-error: true

      - name: Install dependencies
        run: |
          if [ -f "/etc/ssl/certs/ca-certificates.crt" ]; then
            echo "Custom CA certificates found, copying to npm/yarn config"
            cp /etc/ssl/certs/ca-certificates.crt ~/.npmrc
            cp /etc/ssl/certs/ca-certificates.crt ~/.yarnrc
          fi
          npm install --legacy-peer-deps --ignore-ssl-errors=true --verbose
        continue-on-error: true

      - name: Build Gatsby
        run: |
          npm run build
          yarn robots
        continue-on-error: true

      - name: Fix incompatible plugins
        run: sed -i 's/"unstable_shouldOnCreateNode"/"shouldOnCreateNode"/g' node_modules/gatsby-plugin-mdx/gatsby-node.js
        continue-on-error: true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
        continue-on-error: true

      - name: Upload build logs
        uses: actions/upload-artifact@v2
        with:
          name: build-logs
          path: ./public
