name: Publish GitHub Pages

on:
  push:
    branches:
      - master  # Ubah sesuai dengan nama branch utama kamu

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install  # Ubah sesuai dengan perintah instalasi yang kamu gunakan (misal: yarn install)

      - name: Build
        run: npm run build  # Ubah sesuai dengan perintah build yang sesuai (misal: yarn build)

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Ubah jika hasil build ada di direktori lain
