name: Deploy Gatsby Website

on:
  push:
    branches:
      - master  # Branch yang akan memicu workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Menggunakan versi terbaru

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Menggunakan versi terbaru
        with:
          node-version: '18'  # Sesuaikan dengan versi Node.js dari .nvmrc

      - name: Cache dependencies
        uses: actions/cache@v3  # Menggunakan versi terbaru
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: yarn install  # Gunakan npm install jika Anda menggunakan npm

      - name: Build website
        run: NODE_OPTIONS="--max-old-space-size=4096" yarn build  # Menambah alokasi memori hingga 4GB

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: 'z0rs.github.io'  # Ganti dengan domain Anda jika menggunakan custom domain
