name: Deploy Gatsby site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - "master"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Tambahkan langkah untuk menghapus direktori "public" sebelum mengunggah ulang
      - name: Remove existing "public" directory
        run: rm -rf ./public public

      # Tambahkan langkah instalasi dependensi di sini
      - name: Install Dependencies
        run: npm install --legacy-peer-deps # Atau gunakan "yarn install" jika Anda menggunakan Yarn

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
        with:
          # Automatically inject pathPrefix in your Gatsby configuration file.
          #
          # You may remove this line if you want to manage the configuration yourself.
          static_site_generator: gatsby

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: |
            public
            .cache
          key: ${{ runner.os }}-gatsby-build-${{ hashFiles('public') }}
          restore-keys: |
            ${{ runner.os }}-gatsby-build-
      - name: Build with Gatsby
        env:
          PREFIX_PATHS: 'true'
        run: npm run build  # Atau gunakan "yarn run build" jika Anda menggunakan Yarn

      # Langkah upload artifact yang baru dibangun
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: ./public

      # Ganti langkah deployment dengan menggunakan Gatsby Pages Action
      - name: Deploy to GitHub Pages
        uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-branch: master # atau sesuaikan dengan nama branch yang ingin Anda gunakan
          publish-dir: ./public

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        timeout: 600000
        error_count: 10
        reporting_interval: 5000
        artifact_name: public  # Ubah dari "github-pages" menjadi "public"
        preview: false
