name: Deploy Gatsby

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build Gatsby
        run: |
          npm run build
          yarn robots

      - name: Fix incompatible plugins
        run: sed -i 's/"unstable_shouldOnCreateNode"/"shouldOnCreateNode"/g' node_modules/gatsby-plugin-mdx/gatsby-node.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
